# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{inverse_of}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["George Ogata"]
  s.date = %q{2010-02-05}
  s.description = %q{Backport of ActiveRecord 2.3.6's inverse associations.}
  s.email = %q{george.ogata@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.markdown"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "MIT-LICENSE",
     "README.markdown",
     "Rakefile",
     "VERSION",
     "install.rb",
     "inverse_of.gemspec",
     "lib/inverse_of.rb",
     "rails/init.rb",
     "tasks/inverse_of_tasks.rake",
     "test/cases/helper.rb",
     "test/cases/inverse_associations_test.rb",
     "test/fixtures/clubs.yml",
     "test/fixtures/faces.yml",
     "test/fixtures/interests.yml",
     "test/fixtures/men.yml",
     "test/fixtures/sponsors.yml",
     "test/fixtures/zines.yml",
     "test/models/club.rb",
     "test/models/face.rb",
     "test/models/interest.rb",
     "test/models/man.rb",
     "test/models/sponsor.rb",
     "test/models/zine.rb",
     "test/schema/schema.rb",
     "uninstall.rb"
  ]
  s.homepage = %q{http://github.com/oggy/inverse_of}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Backport of ActiveRecord 2.3.6's inverse associations.}
  s.test_files = [
    "test/cases/helper.rb",
     "test/cases/inverse_associations_test.rb",
     "test/models/club.rb",
     "test/models/face.rb",
     "test/models/interest.rb",
     "test/models/man.rb",
     "test/models/sponsor.rb",
     "test/models/zine.rb",
     "test/schema/schema.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

